# Datasource
spring:
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Server
server:
  port: 8081

# Bet DAO urls
bet:
  url:
    five-out-of-ninety: https://bet.szerencsejatek.hu/cmsfiles/otos.csv
    six-out-of-forty-five: https://bet.szerencsejatek.hu/cmsfiles/hatos.csv
    scandinavian: https://bet.szerencsejatek.hu/cmsfiles/skandi.csv
    joker: https://bet.szerencsejatek.hu/cmsfiles/joker.csv

# Swagger
swagger:
  path-selector-pattern: /(lottery|retrieve)/.+
  title: SmartPlatform - Lottery Service
  description: Lottery service for different lottery types.
  version: 1.0
  terms-of-service-url:
  contact-name: Balázs Gábor
  contact-url: https://github.com/ProudProgrammer
  contact-email: mail.gabor.balazs@gmail.com
  license: GNU General Public License
  license-url: https://www.gnu.org/licenses/gpl-3.0.en.html

# CustomLoggingFilter
customloggingfilter:
  enabled: true
  logrequest: true
  logresponse: true
  request-querystring: true
  request-clientinfo: true
  request-headers: true
  request-payload: true
  # request-messageprefix: Request [
  # request-messagesuffix: ]
  response-headers: true
  response-payload: true
  # response-messageprefix: Response [
  # response-messagesuffix: ]

# LoggerAspect
loggeraspect:
  enabled: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"